version: 2
jobs:
  build:
    working_directory: ~/morphlog
    docker:
      - image: cypress/base:8
    steps:
      - checkout
      #- run:
      #    name: update-npm
      #    command: 'sudo npm install -g npm@latest'
      - run:
          name: install-npm-server
          command: npm install
      - run:
          name: install-npm-client
          command: cd client && npm install
      - run:
          name: test server
          command: npm test
      #- run:
      #    name: test client
      #    command: cd client && npm test
      - run:
          name: test e2e
          command: 'npm run integration'