version: 2
jobs:
  build:
    working_directory: ~/morphlog
    docker:
      - image: cypress/base:8
    steps:
      - checkout
      #- run:
      #    name: update-npm
      #    command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: v1-server-dependency-cache-{{ checksum "./server/package.json" }}
      - run:
          name: install-npm-server
          command: cd server && npm install --no-save
      - save_cache:
          key: v1-server-dependency-cache-{{ checksum "./server/package.json" }}
          paths:
            - ./node_modules
      - restore_cache:
          key: v1-client-dependency-cache-{{ checksum "./client/package.json" }}
      - run:
          name: install-npm-client
          command: cd client && npm install --no-save
      - save_cache:
          key: v1-client-dependency-cache-{{ checksum "./client/package.json" }}
          paths:
            - ./client/node_modules
      - restore_cache:
          key: v1-e2e-dependency-cache-{{ checksum "./e2e/package.json" }}
      - run:
          name: install-npm-e2e
          command: cd e2e && npm install --no-save
      - save_cache:
          key: v1-e2e-dependency-cache-{{ checksum "./e2e/package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test server
          command: cd server && npm test
      - run:
          name: test client
          command: cd client && npm test
      #- run:
      #    name: lint client
      #    command: cd client && npm run lint
      - run:
          name: test e2e
          command: cd e2e && npm run integration || echo 0
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
